FROM openjdk:8-jdk-alpine

# Installation de Python 3 et pip
RUN apk add --no-cache python3 py3-pip

# Installation de Spark
ENV SPARK_VERSION=3.4.0
RUN apk add --no-cache bash && \
    wget -q "https://archive.apache.org/dist/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop3.tgz" && \
    tar -xzf "spark-$SPARK_VERSION-bin-hadoop3.tgz" -C /opt/ && \
    mv "/opt/spark-$SPARK_VERSION-bin-hadoop3" /opt/spark

# Mise à jour du PATH
ENV PATH="/opt/spark/bin:${PATH}"
