version: '2'
services:
  # Jupyter with PySpark
  ed-pyspark-jupyter:
    image: jupyter/pyspark-notebook:spark-3.3.0
    user: root
    container_name: ed-pyspark-jupyter-lab
    ports:
      - 8888:8888
      - 4040:4040
    environment:
      JUPYTER_PORT: 8888
      SPARK_UI_PORT: 4040
      GRANT_SUDO: yes
      SPARK_MASTER: spark://ed-spark-master:7077
    volumes:
      - streaming_data:/data:rw
    depends_on:
      - ed-spark-master
      - ed-kafka

  # Zookeeper service
  ed-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ed-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka service
  ed-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ed-kafka
    depends_on:
      - ed-zookeeper
    ports:
      - 9092:9092
    volumes:
      - streaming_data:/data:rw
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ed-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ed-kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "raw:1:1"

  # Spark Master
  ed-spark-master:
    image: bitnami/spark:3.3
    container_name: ed-spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=ed-spark-master
      - SPARK_LOCAL_DIRS=/data
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - streaming_data:/data:rw

  # Spark Worker 1
  ed-spark-worker-1:
    image: bitnami/spark:3.3
    container_name: ed-spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://ed-spark-master:7077
      - SPARK_LOCAL_DIRS=/data
    depends_on:
      - ed-spark-master
    ports:
      - 8081:8081
    volumes:
      - streaming_data:/data:rw

  # Spark Worker 2
  ed-spark-worker-2:
    image: bitnami/spark:3.3
    container_name: ed-spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://ed-spark-master:7077
      - SPARK_LOCAL_DIRS=/data
    depends_on:
      - ed-spark-master
    ports:
      - 8082:8082
    volumes:
      - streaming_data:/data:rw

volumes:
  streaming_data:
